# Pandas Exercises

In [29]:
import pandas as pd

url = "https://raw.githubusercontent.com/BeaverWorksMedlytics2020/Data_Public/master/NotebookExampleData/Week1/diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

Read in csv above to a pandas dataframe

In [30]:
# YOUR CODE HERE
import pandas as pd

df = pd.read_csv(url, names=names)
df.head()

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

Print out the age and class of the 100th patient

In [43]:
# YOUR CODE HERE
df.loc[99, ['age', 'class']]

age      31.0
class     1.0
Name: 99, dtype: float64

Write code to figure out how many people are classified as not having diabetes, class is 0

In [57]:
# YOUR CODE HERE
df[df['class'] == 0].shape[0]

500

Write code to figure out how many people are classified as having diabetes, class is 1

In [68]:
# YOUR CODE HERE
df[df['class'] == 1].shape[0]

268

What percent of people have diabetes in the study

In [ ]:
# YOUR CODE HERE
d_count= (df['class'] == 1).sum()
total = df.shape[0]
percentage = (d_count / total) * 100
print(percentage)

np.float64(34.89583333333333)

Print out the `"pres"` and `"class"` (no other columns) for the first 5 people

In [87]:
# YOUR CODE HERE
df.loc[0:5, ['pres', 'class']]

   pres  class
0    72      1
1    66      0
2    64      1
3    66      0
4    40      1
5    74      0

Run the cell below, it will print out the correlation among the columns

In [88]:
data = df
data.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

What column has the highest correlation with class? Find the mean() value of that column

In [107]:
# YOUR CODE HER
df['plas'].mean()

np.float64(120.89453125)

Create a new dataframe with only people that are above the mean found in the above cell.

In [95]:
# YOUR CODE HERE
df2 = df[df['plas'] > 120]

Create a new dataframe that only includes people who are above the average value for each column in the dataset. In other words, find the average value for each column, and then find which users have values above all of these average column values.

In [100]:
# YOUR CODE HERE
col_means = df.mean()
col_means
df_above_avg = df[df > col_means]

*Note: the next 3 problems were not explicitly shown in our tutorial—being able to effectively google and look through documentation is a very important coding tool!* ¯\\\_(ツ)_/¯

Ignoring the index (resetting the index to 0) and using the dataframe from the cell above, sort the values based on `"skin"`, `"test"`, and `"pedi"` values in ascending order. Please write this in one line.

In [101]:
# YOUR CODE HERE
df_above_avg.sort_values(['skin','test','pedi'], ascending=True)
print(df_above_avg)

     preg   plas  pres  skin   test  mass   pedi   age  class
0     6.0  148.0  72.0  35.0    NaN  33.6  0.627  50.0    1.0
1     NaN    NaN   NaN  29.0    NaN   NaN    NaN   NaN    NaN
2     8.0  183.0   NaN   NaN    NaN   NaN  0.672   NaN    1.0
3     NaN    NaN   NaN  23.0   94.0   NaN    NaN   NaN    NaN
4     NaN  137.0   NaN  35.0  168.0  43.1  2.288   NaN    1.0
..    ...    ...   ...   ...    ...   ...    ...   ...    ...
763  10.0    NaN  76.0  48.0  180.0  32.9    NaN  63.0    NaN
764   NaN  122.0  70.0  27.0    NaN  36.8    NaN   NaN    NaN
765   5.0  121.0  72.0  23.0  112.0   NaN    NaN   NaN    NaN
766   NaN  126.0   NaN   NaN    NaN   NaN    NaN  47.0    1.0
767   NaN    NaN  70.0  31.0    NaN   NaN    NaN   NaN    NaN

[768 rows x 9 columns]

Now let's find the 4 largest values for `"age"`

In [102]:
# YOUR CODE HERE
df['age'].nlargest(4)

459    81
453    72
666    70
123    69
Name: age, dtype: int64

Now find the smallest 4 values for `"pedi"` and `"plas"` in reverse order (smallest to largest).

In [104]:
# YOUR CODE HERE
print(df['pedi'].nsmallest(4).sort_values())
print(df['plas'].nsmallest(4).sort_values())

268    0.078
180    0.084
149    0.085
567    0.085
Name: pedi, dtype: float64
75     0
182    0
342    0
349    0
Name: plas, dtype: int64